defaults:
    - _self_
    - paths: mac
    - data: cifar10_pycil

hydra:
    run:
        dir: ${paths.run_dir}
    job_logging:
        formatters:
            simple:
                format: "%(asctime)s - %(message)s"
                datefmt: "%Y-%m-%d %H:%M:%S"

model:
    name: resnet18
    weights: 
    load_checkpoint:
    write_checkpoint: ${paths.run_dir}/checkpoints/

optim:
    loss: cross_entropy
    label_smoothing: 0.0

train:
    run: true
    batch_size: 100

val:
    run: true
    batch_size: 10000

eval:
    run: false
    batch_size: 10000


seed: 202
device: cpu
