hydra:
    job_logging:
        formatters:
            simple:
                format: "%(asctime)s - %(message)s"
                datefmt: "%Y-%m-%d %H:%M:%S"

root_dir: /Users/daniellerothermel/drotherm/
data_dir: ${.root_dir}data
log_dir: ${.root_dir}logs
