root: /Users/daniellerothermel/drotherm
proj_dir_name:
data: ${paths.root}/data
logs: ${paths.root}/logs

my_data: ${paths.data}/${paths.proj_dir_name}
my_logs: ${paths.logs}/${paths.proj_dir_name}

run_dir: ${paths.my_logs}/bs${train.batch_size}/lr${optim.lr}/wd${optim.weight_decay}/tup${data.train.use_percent}/xft${data.transform_type}/s${seed}/${weight_type}/${model.weights}/${now:%Y-%m-%d-%H-%M-%s}

dataset_cache_root: ${paths.data}/${data.name}/
agg_results: ${paths.my_data}/cifar10/cluster_runs/lr_wd_init_v0


