defaults:
    - paths: cluster
    - data: cifar10_pycil
    - _self_

paths:
    proj_dir_name: dr_gen

hydra:
    run:
        dir: ${paths.run_dir}
    job_logging:
        formatters:
            simple:
                format: "%(asctime)s - %(message)s"
                datefmt: "%Y-%m-%d %H:%M:%S"

metrics:
    loggers:
        - hydra
        - json
    init:
        batch_size: list
        loss: batch_weighted_avg_list
        acc1: batch_weighted_avg_list
        acc5: batch_weighted_avg_list
        grad_norm: batch_weighted_avg_list
        lr: batch_weighted_avg_list

model:
    source: timm
    name: resnet18
    weights: resnet18.a1_in1k

optim:
    loss: cross_entropy
    label_smoothing: 0.0
    name: sgd
    weight_decay: 1e-4
    clip_grad_norm:
    lr: 0.1
    step_size: 90
    gamma: 0.1
    momentum: 0.9
    eps: 0.0316
    alpha: 0.9
    nesterov: false
    lr_scheduler: timm_cosine
    lr_min: 0.0
    warmup_epochs: 5
    warmup_start_lr: 0.0
    cycle_limit: 1

train:
    run: true
    batch_size: 500

val:
    run: true
    batch_size: 500

eval:
    run: true
    batch_size: 500


seed: 0
weight_type: pretrained
device: cuda
epochs: 50
load_checkpoint:
write_checkpoint: 
