defaults:
    - paths: mac
    - data: cifar10_pycil
    - _self_

paths:
    proj_dir_name: dr_util

hydra:
    run:
        dir: ${paths.run_dir}
    job_logging:
        formatters:
            simple:
                format: "%(asctime)s - %(message)s"
                datefmt: "%Y-%m-%d %H:%M:%S"

metrics:
    loggers:
        - hydra
        - json
    init:
        batch_size: list
        loss: batch_weighted_avg_list
        acc1: batch_weighted_avg_list
        acc5: batch_weighted_avg_list

model:
    name: resnet18
    weights: 

optim:
    loss: cross_entropy
    label_smoothing: 0.0
    name: sgd
    weight_decay: 1e-4
    clip_grad_norm:
    lr: 0.1
    momentum: 0.9
    eps: 0.0316
    alpha: 0.9
    nesterov: false
    lr_scheduler: steplr
    lr_step_size: 30
    lr_gamma: 0.1
    lr_min: 0.0
    lr_warmup_epochs: 0

train:
    run: true
    batch_size: 100

val:
    run: true
    batch_size: 10000

eval:
    run: false
    batch_size: 10000


seed: 202
device: cpu
epochs: 3
load_checkpoint:
write_checkpoint: ${paths.run_dir}/checkpoints/
